### ISSUE TITLE
AK hints' indicator sometimes displays the incorrect AK

### ISSUE THREAD

**Issue by st-AR-gazer** [XertroV/tm-ak-hints#1]
AK indicator sometimes doesn't show the correct AK

![image](https://github.com/XertroV/tm-ak-hints/assets/132480072/60227e4e-f452-43ab-90f9-932c02784c8a)

Should easily be fixed by just adding if the car's wheels are more than 80% for a few frames :)

**Comment by XertroV** [comment]
there is already code to do this (it waits 40ms or 4 frames)

how did you get it in that state?

**Comment by st-AR-gazer** [comment]
Got it again:
![image](https://github.com/XertroV/tm-ak-hints/assets/132480072/ba93ca26-494a-4b85-bad7-6106a656c2ab)
It seems to happen when pressing reset and the ak at (almost?) the same time.

**Comment by XertroV** [comment]
okay, might be a frame order thing. But the desync detection should pick that up. will look into it

**Comment by st-AR-gazer** [comment]
@XertroV I think I found the reason for this issue, when pressing the AK reset button and then pressing another AK before releasing the AK reset the display bugs, (since pressing an AK whilst holding down the reset for some reason doesn't set it to the new AK)

**Comment by XertroV** [comment]
Yeah okay. Seems like AK5 has priority while it's held down. So I need some slightly different logic to ignore the first-observed logic for the other AKs.
